// Generated by scripts/solve-levels.mts — do not edit by hand.
import type { Solution } from './engine';

export const SOLUTIONS: (Solution & { par: number })[] = [
  {
    par: 1,
    placements: [
      {
        x: 4,
        y: 5,
        kind: 'mirror',
        orient: 0,
      },
    ],
    pivots: {},
  },
  {
    par: 2,
    placements: [
      {
        x: 1,
        y: 4,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 1,
        y: 1,
        kind: 'mirror',
        orient: 0,
      },
    ],
    pivots: {},
  },
  {
    par: 0,
    placements: [],
    pivots: {
      '3,0': 1,
      '3,4': 1,
      '6,4': 1,
    },
  },
  {
    par: 5,
    placements: [
      {
        x: 6,
        y: 4,
        kind: 'mirror',
        orient: 1,
      },
      {
        x: 2,
        y: 4,
        kind: 'mirror',
        orient: 1,
      },
      {
        x: 2,
        y: 2,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 4,
        y: 2,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 4,
        y: 0,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 2,
    placements: [
      {
        x: 3,
        y: 4,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 5,
        y: 4,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 4,
    placements: [
      {
        x: 3,
        y: 7,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 3,
        y: 6,
        kind: 'splitter',
        orient: 1,
      },
      {
        x: 5,
        y: 7,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 1,
        y: 6,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 3,
    placements: [
      {
        x: 1,
        y: 6,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 3,
        y: 6,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 1,
        y: 0,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 3,
    placements: [
      {
        x: 3,
        y: 6,
        kind: 'splitter',
        orient: 1,
      },
      {
        x: 6,
        y: 4,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 0,
        y: 6,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {
      '3,4': 0,
    },
  },
  {
    par: 2,
    placements: [
      {
        x: 5,
        y: 7,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 5,
        y: 1,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 4,
    placements: [
      {
        x: 2,
        y: 1,
        kind: 'mirror',
        orient: 1,
      },
      {
        x: 2,
        y: 8,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 4,
        y: 7,
        kind: 'mirror',
        orient: 1,
      },
      {
        x: 4,
        y: 0,
        kind: 'mirror',
        orient: 0,
      },
    ],
    pivots: {},
  },
  {
    par: 3,
    placements: [
      {
        x: 2,
        y: 4,
        kind: 'splitter',
        orient: 1,
      },
      {
        x: 3,
        y: 4,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 3,
        y: 0,
        kind: 'mirror',
        orient: 0,
      },
    ],
    pivots: {},
  },
  {
    par: 2,
    placements: [
      {
        x: 6,
        y: 7,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 0,
        y: 7,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 4,
    placements: [
      {
        x: 0,
        y: 7,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 0,
        y: 4,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 1,
        y: 7,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 5,
        y: 4,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
  {
    par: 5,
    placements: [
      {
        x: 3,
        y: 7,
        kind: 'splitter',
        orient: 0,
      },
      {
        x: 3,
        y: 5,
        kind: 'splitter',
        orient: 1,
      },
      {
        x: 5,
        y: 7,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 5,
        y: 0,
        kind: 'mirror',
        orient: 0,
      },
      {
        x: 0,
        y: 2,
        kind: 'mirror',
        orient: 1,
      },
    ],
    pivots: {},
  },
];
