// Verifies every level is solvable and regenerates src/game/solutions.ts
// Run with: node scripts/solve-levels.mts   (Node >= 23.6, native TS stripping)
import { writeFileSync } from 'node:fs';
import { parseLevel, solve, trace } from '../src/game/engine.ts';
import { LEVELS } from '../src/game/levels.ts';

let failed = false;
const out: unknown[] = [];

LEVELS.forEach((def, i) => {
  const level = parseLevel(def, i);
  const start = trace(level, level.initialPieces);
  const t0 = Date.now();
  const solution = solve(level);
  const ms = Date.now() - t0;
  if (!solution) {
    failed = true;
    console.log(`#${i + 1} ${def.name}: UNSOLVABLE (${ms}ms)`);
    out.push(null);
    return;
  }
  const par = solution.placements.length;
  const flags = [
    start.solved ? 'ALREADY SOLVED AT START' : '',
    par < def.inventory.mirror + def.inventory.splitter
      ? `spare ${def.inventory.mirror + def.inventory.splitter - par}`
      : '',
  ].filter(Boolean);
  if (start.solved) failed = true;
  console.log(
    `#${i + 1} ${def.name}: par ${par} ${JSON.stringify(
      solution.placements,
    )} pivots=${JSON.stringify(solution.pivots)} ${ms}ms ${flags.join(' ')}`,
  );
  out.push({ par, ...solution });
});

writeFileSync(
  new URL('../src/game/solutions.ts', import.meta.url),
  `// Generated by scripts/solve-levels.mts — do not edit by hand.\nimport type { Solution } from './engine';\n\nexport const SOLUTIONS: (Solution & { par: number })[] = ${JSON.stringify(
    out,
    null,
    2,
  )};\n`,
);
process.exit(failed ? 1 : 0);
